name: Terraform Plan
description: Plan Terraform changes
inputs:
  AZURE_CREDENTIALS:
    description: 'Azure credentials'
    required: true
runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Fetch pull request head
      if: github.event.issue.pull_request
      shell: bash
      run: |
        git fetch origin pull/${{ github.event.issue.number }}/head:pr-find-commit
        git checkout pr-find-commit

    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ inputs.AZURE_CREDENTIALS }}
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Initialize and Plan Terraform changes
      shell: bash
      run: cd terraform && terraform init && terraform plan
