name: Terraform Plan

on:
  workflow_dispatch:

permissions: 
  contents: read
  id-token: write
  pull-requests: write

defaults:
  run:
    working-directory: terraform

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/terraform-plan
        with:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        id: plan
