name: Terraform Apply

on:
    workflow_dispatch:
    workflow_call:

permissions: 
  contents: read
  id-token: write
  pull-requests: write

defaults:
  run:
    working-directory: terraform

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - if : github.event.issue.pull_request
        run: |
          git fetch origin pull/${{ github.event.issue.number }}/head:pr-find-commit
          git checkout pr-find-commit

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - uses: hashicorp/setup-terraform@v3

      - run: terraform init

      - run: terraform apply -auto-approve
