name: Terraform Comment Triggers

on:
  issue_comment:
    types: [created, edited]

permissions: 
  contents: read
  id-token: write
  pull-requests: write

defaults:
  run:
    working-directory: terraform

jobs:
  terraform:
    runs-on: ubuntu-latest
    if: (contains(github.event.comment.body, 'terraform plan') || contains(github.event.comment.body, 'terraform apply')) && github.event.issue.pull_request
    steps:
      - name: "Update comment"
        if: (contains(github.event.comment.body, 'terraform plan') || contains(github.event.comment.body, 'terraform apply')) && github.event.issue.pull_request
        uses: actions/github-script@v7
        with:
          script: |
            const { issue: { number: issue_number }, repo: { owner, repo }, payload  } = context;
            await github.rest.issues.updateComment({
              owner,
              repo,
              comment_id: payload.comment.id,
              body: [
                `> ${payload.comment.body}`,
                `Running terraform plan...`,
                `[View job](https://github.com/${owner}/${repo}/actions/runs/${context.runId})`
              ].filter(Boolean).join('\n\n')
            });

      - uses: actions/checkout@v4

      - run: |
          git fetch origin pull/${{ github.event.issue.number }}/head:pr-find-commit
          git checkout pr-find-commit

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - uses: hashicorp/setup-terraform@v3

      - run: terraform init

      - if: (contains(github.event.comment.body, 'terraform plan') || contains(github.event.comment.body, 'terraform apply')) && github.event.issue.pull_request
        continue-on-error: true
        run: terraform plan -no-color
        id: plan

      - name: Success message
        if: steps.plan.outcome == 'success'
        uses: actions/github-script@v7
        continue-on-error: true
        with:
          script: |
            const { issue: { number: issue_number }, repo: { owner, repo }, payload  } = context;
            await github.rest.issues.updateComment({
              owner,
              repo,
              comment_id: payload.comment.id,
              body: [
                `> ${payload.comment.body}`,
                `:rocket: Successfully ran terraform plan!`,
                `[View job](https://github.com/${owner}/${repo}/actions/runs/${context.runId})`
              ].filter(Boolean).join('\n\n')
            });
      
      - name: "Update comment"
        if: contains(github.event.comment.body, 'terraform apply') && github.event.issue.pull_request
        uses: actions/github-script@v7
        with:
          script: |
            const { issue: { number: issue_number }, repo: { owner, repo }, payload  } = context;
            await github.rest.issues.updateComment({
              owner,
              repo,
              comment_id: payload.comment.id,
              body: [
                `> ${payload.comment.body}`,
                `Running terraform apply...`,
                `[View job](https://github.com/${owner}/${repo}/actions/runs/${context.runId})`
              ].filter(Boolean).join('\n\n')
            });

      - if: contains(github.event.comment.body, 'terraform apply') && github.event.issue.pull_request
        continue-on-error: true
        run: terraform apply -auto-approve -no-color
        id: apply

      - name: Success message
        if: steps.apply.outcome == 'success' && steps.apply.outcome != 'skipped'
        uses: actions/github-script@v7
        continue-on-error: true
        with:
          script: |
            const { repo: { owner, repo }, payload  } = context;
            const currentComment = await github.rest.issues.getComment({
              owner, repo, comment_id: payload.comment.id
            });
            const body = currentComment.data.body.replace(
              /^:rocket:.*$/m,
              ':rocket: terraform apply ran successfully!'
            );
            await github.rest.issues.updateComment({
              owner,
              repo,
              comment_id: payload.comment.id,
              body
            });

      - name: Failure message
        if: steps.plan.outcome == 'failure' || steps.apply.outcome == 'failure'
        uses: actions/github-script@v7
        continue-on-error: true
        with:
          script: |
            const { repo: { owner, repo }, payload  } = context;
            const currentComment = await github.rest.issues.getComment({
              owner, repo, comment_id: payload.comment.id
            });
            const body = currentComment.data.body.replace(
              /^:rocket:.*$/m,
              ':red_circle: terraform plan/apply failed!'
            );
            await github.rest.issues.updateComment({
              owner,
              repo,
              comment_id: payload.comment.id,
              body
            });
